### PR TITLE
feat: Added automatic tab switching dependent on OS used by the user. 

### PR DESCRIPTION
**Pull request by markolo25**

### CODE REVIEW

**Comment by markolo25** [comment]
What is a semantic pull request?

**Comment by maxandersen** [comment]
trying to load https://jbangdev-jbang-dev-preview-pr-44.surge.sh/download/ on ipad the tabs dont show up - just one long list.

https://jbang.dev works.

so something isn't loading right ?

**Comment by markolo25** [comment]
i will look into the ipad issue

**Comment by maxandersen** [comment]
It's an iPad pro I'm testing on

**Comment by markolo25** [comment]
I'm going to try to reproduce the issue via BrowserStack, I have the 2021 iPad Pro, with iOS 15.3.1 testing it on safari.

**Comment by markolo25** [comment]
If you have some time, I've tried every iPad on browser stack, and all the iPads in my house, which is a pro 11 inch 2021 and an 7th gen plain iPad both on the latest iOS.

**Comment by maxandersen** [comment]
sorry - i missed this update - i tried again with ipad and this time it worked.

Thanks alot !

**Review by maxandersen — APPROVED** [review]

**Comment by maxandersen** [comment]
@all-contributors please add @markolo25  for code

**Pull request merged**
